FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build-env
WORKDIR /bin

# Copy csproj and restore as distinct layers
COPY *.csproj ./
COPY NuGet.Config ./ 
COPY Lavalink.jar ./
EXPOSE 2332
RUN dotnet restore

# Copy everything else and build
COPY . ./
RUN dotnet publish -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /bin
COPY --from=build-env /bin/out .
ENTRYPOINT ["dotnet", "Vinyl.dll"]